USE [ApostaEmCorridas_Banco]
GO

/****** Object:  Table [dbo].[CAVALO]    Script Date: 27/11/2025 20:52:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAVALO](
	[Numero_Cavalo] [int] NOT NULL,
	[Nome] [varchar](45) NOT NULL,
	[Altura] [float] NOT NULL,
	[Peso] [float] NOT NULL,
	[Numero_de_Corridas] [int] NOT NULL,
	[Numero_de_Vitorias] [int] NOT NULL,
	[Raca] [varchar](45) NOT NULL,
	[StatusCavalo] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Numero_Cavalo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_CAVALO] UNIQUE NONCLUSTERED 
(
	[Numero_Cavalo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAVALO] ADD  DEFAULT ((0)) FOR [StatusCavalo]
GO


