USE [ApostaEmCorridas_Banco]
GO

/****** Object:  Table [dbo].[INSCRICAO_CORRIDA]    Script Date: 27/11/2025 20:52:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INSCRICAO_CORRIDA](
	[Id_Inscricao] [int] IDENTITY(1,1) NOT NULL,
	[Id_Corrida] [int] NOT NULL,
	[Id_Cavalo] [int] NOT NULL,
 CONSTRAINT [PK_Inscricao] PRIMARY KEY CLUSTERED 
(
	[Id_Inscricao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[INSCRICAO_CORRIDA]  WITH CHECK ADD  CONSTRAINT [FK_Cavalo_Inscricao] FOREIGN KEY([Id_Cavalo])
REFERENCES [dbo].[CAVALO] ([Numero_Cavalo])
GO

ALTER TABLE [dbo].[INSCRICAO_CORRIDA] CHECK CONSTRAINT [FK_Cavalo_Inscricao]
GO

ALTER TABLE [dbo].[INSCRICAO_CORRIDA]  WITH CHECK ADD  CONSTRAINT [FK_Corrida_Inscricao] FOREIGN KEY([Id_Corrida])
REFERENCES [dbo].[CORRIDA] ([Id_Corrida])
GO

ALTER TABLE [dbo].[INSCRICAO_CORRIDA] CHECK CONSTRAINT [FK_Corrida_Inscricao]
GO


