USE [ApostaEmCorridas_Banco]
GO

/****** Object:  Table [dbo].[VOLTA]    Script Date: 27/11/2025 20:52:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VOLTA](
	[Id_Volta] [int] IDENTITY(1,1) NOT NULL,
	[Id_Corrida] [int] NOT NULL,
	[Id_Cavalo] [int] NOT NULL,
	[NumeroVolta] [int] NOT NULL,
	[TempoVolta] [time](7) NOT NULL,
	[DistanciaPercorrida] [decimal](10, 2) NULL,
 CONSTRAINT [PK_VOLTA] PRIMARY KEY CLUSTERED 
(
	[Id_Volta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VOLTA]  WITH CHECK ADD  CONSTRAINT [FK_VOLTA_CAVALO] FOREIGN KEY([Id_Cavalo])
REFERENCES [dbo].[CAVALO] ([Numero_Cavalo])
GO

ALTER TABLE [dbo].[VOLTA] CHECK CONSTRAINT [FK_VOLTA_CAVALO]
GO

ALTER TABLE [dbo].[VOLTA]  WITH CHECK ADD  CONSTRAINT [FK_VOLTA_CORRIDA] FOREIGN KEY([Id_Corrida])
REFERENCES [dbo].[CORRIDA] ([Id_Corrida])
GO

ALTER TABLE [dbo].[VOLTA] CHECK CONSTRAINT [FK_VOLTA_CORRIDA]
GO


