USE [ApostaEmCorridas_Banco]
GO

/****** Object:  Table [dbo].[RESULTADO_CORRIDA]    Script Date: 27/11/2025 20:52:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RESULTADO_CORRIDA](
	[Id_Resultado] [int] IDENTITY(1,1) NOT NULL,
	[Id_Corrida] [int] NOT NULL,
	[Id_Cavalo] [int] NOT NULL,
	[Posicao] [int] NULL,
	[Duracao] [time](7) NOT NULL,
 CONSTRAINT [PK_RESULTADO_CORRIDA] PRIMARY KEY CLUSTERED 
(
	[Id_Resultado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RESULTADO_CORRIDA]  WITH CHECK ADD  CONSTRAINT [FK_CAVALO] FOREIGN KEY([Id_Cavalo])
REFERENCES [dbo].[CAVALO] ([Numero_Cavalo])
GO

ALTER TABLE [dbo].[RESULTADO_CORRIDA] CHECK CONSTRAINT [FK_CAVALO]
GO

ALTER TABLE [dbo].[RESULTADO_CORRIDA]  WITH CHECK ADD  CONSTRAINT [FK_CORRIDA] FOREIGN KEY([Id_Corrida])
REFERENCES [dbo].[CORRIDA] ([Id_Corrida])
GO

ALTER TABLE [dbo].[RESULTADO_CORRIDA] CHECK CONSTRAINT [FK_CORRIDA]
GO


