USE [ApostaEmCorridas_Banco]
GO

/****** Object:  Table [dbo].[APOSTA]    Script Date: 27/11/2025 20:50:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APOSTA](
	[Aposta_ID] [int] IDENTITY(1,1) NOT NULL,
	[CavaloApostado] [int] NOT NULL,
	[Apostador] [int] NOT NULL,
	[ValorApostado] [money] NOT NULL,
	[StatusAposta] [int] NOT NULL,
	[Id_Corrida] [int] NOT NULL,
	[valorPremio] [money] NOT NULL,
 CONSTRAINT [PK_APOSTA] PRIMARY KEY CLUSTERED 
(
	[Aposta_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[APOSTA] ADD  DEFAULT ((0)) FOR [valorPremio]
GO

ALTER TABLE [dbo].[APOSTA]  WITH CHECK ADD  CONSTRAINT [FK_APOSTA_CAVALO] FOREIGN KEY([CavaloApostado])
REFERENCES [dbo].[CAVALO] ([Numero_Cavalo])
GO

ALTER TABLE [dbo].[APOSTA] CHECK CONSTRAINT [FK_APOSTA_CAVALO]
GO

ALTER TABLE [dbo].[APOSTA]  WITH CHECK ADD  CONSTRAINT [FK_APOSTA_CORRIDA] FOREIGN KEY([Id_Corrida])
REFERENCES [dbo].[CORRIDA] ([Id_Corrida])
GO

ALTER TABLE [dbo].[APOSTA] CHECK CONSTRAINT [FK_APOSTA_CORRIDA]
GO

ALTER TABLE [dbo].[APOSTA]  WITH CHECK ADD  CONSTRAINT [FK_Apostador_Aposta] FOREIGN KEY([Apostador])
REFERENCES [dbo].[APOSTADOR] ([Numero])
GO

ALTER TABLE [dbo].[APOSTA] CHECK CONSTRAINT [FK_Apostador_Aposta]
GO


