USE [master]
GO

/****** Object:  Database [ApostaEmCorridas_Banco]    Script Date: 27/11/2025 20:48:34 ******/
CREATE DATABASE [ApostaEmCorridas_Banco]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ApostaEmCorridas_Banco', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ApostaEmCorridas_Banco.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ApostaEmCorridas_Banco_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ApostaEmCorridas_Banco_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ApostaEmCorridas_Banco].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET ARITHABORT OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET  MULTI_USER 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET QUERY_STORE = ON
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ApostaEmCorridas_Banco] SET  READ_WRITE 
GO


